package cosc_603;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class AgeCalcTest extends BaseTest {

    @Test
    public void ageCalc0() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 908));
        driver.findElement(By.linkText("Age Calculator")).click();
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '11']")).click();
        }
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '13']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".verybigtext")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("Age:\\\\n2 days\\\\nor 48 hours\\\\nor 2,880 minutes\\\\nor 172,800 seconds"));
        driver.findElement(By.cssSelector(".verybigtext")).click();
    }

    @Test
    public void ageCalc1() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 908));
        driver.findElement(By.linkText("Age Calculator")).click();
        driver.findElement(By.id("today_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Mar']")).click();
        }
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '4']")).click();
        }
        driver.findElement(By.id("today_Year_ID")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td > table > tbody > tr")).click();
        driver.findElement(By.id("today_Year_ID")).sendKeys("1992");
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '13']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".verybigtext")).click();
        assertThat(driver.getTitle(), is("Age Calculator"));
        driver.findElement(By.cssSelector("h1")).click();
        assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Age Calculator"));
        driver.findElement(By.cssSelector(".verybigtext")).click();
    }

    @Test
    public void ageCalc2() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 908));
        driver.findElement(By.linkText("Age Calculator")).click();
        driver.findElement(By.id("today_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Apr']")).click();
        }
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '12']")).click();
        }
        driver.findElement(By.cssSelector("tr:nth-child(1) > td > table > tbody > tr")).click();
        driver.findElement(By.id("today_Year_ID")).sendKeys("1980");
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '12']")).click();
        }
        driver.findElement(By.cssSelector("table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(2)")).click();
        driver.findElement(By.id("ageat_Year_ID")).sendKeys("2018");
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".verybigtext")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("Age:\\\\n1 months 0 days\\\\nor 4 weeks 2 days\\\\nor 30 days\\\\nor 720 hours\\\\nor 43,200 minutes\\\\nor 2,592,000 seconds"));
        driver.findElement(By.cssSelector(".verybigtext")).click();
    }

    @Test
    public void ageCalc3() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(816, 854));
        driver.findElement(By.linkText("Age Calculator")).click();
        driver.findElement(By.id("today_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Jan']")).click();
        }
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '12']")).click();
        }
        driver.findElement(By.id("today_Year_ID")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) > td > table > tbody > tr")).click();
        driver.findElement(By.id("today_Year_ID")).sendKeys("1956");
        driver.findElement(By.id("ageat_Month_ID")).click();
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '12']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
        driver.findElement(By.id("content")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("Age:\\\\n4 months 0 days\\\\nor 17 weeks 2 days\\\\nor 121 days\\\\nor 2,904 hours\\\\nor 174,240 minutes\\\\nor 10,454,400 seconds"));
    }

    @Test
    public void ageCalc4() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 999));
        driver.findElement(By.linkText("Age Calculator")).click();
        driver.findElement(By.cssSelector("h1")).click();
        assertThat(driver.getTitle(), is("Age Calculator"));
        driver.findElement(By.id("today_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Jan']")).click();
        }
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '12']")).click();
        }
        driver.findElement(By.cssSelector("tr:nth-child(1) > td > table > tbody > tr")).click();
        driver.findElement(By.id("today_Year_ID")).sendKeys("1950");
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '12']")).click();
        }
        driver.findElement(By.id("ageat_Year_ID")).click();
        driver.findElement(By.id("ageat_Year_ID")).sendKeys("2012");
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".verybigtext")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("Age:\\\\n4 months 0 days\\\\nor 17 weeks 2 days\\\\nor 121 days\\\\nor 2,904 hours\\\\nor 174,240 minutes\\\\nor 10,454,400 seconds"));
        driver.findElement(By.cssSelector(".verybigtext")).click();
        driver.findElement(By.cssSelector(".verybigtext")).click();
        driver.findElement(By.cssSelector(".verybigtext")).click();
    }

    @Test
    public void ageCalc5() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(500, 647));
        driver.findElement(By.linkText("Age Calculator")).click();
        assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("The Age Calculator can determine the age or interval between two dates. The calculated age will be displayed in years, months, weeks, days, hours, minutes, and seconds."));
        driver.findElement(By.id("today_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Feb']")).click();
        }
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '16']")).click();
        }
        driver.findElement(By.id("today_Year_ID")).click();
        driver.findElement(By.id("today_Year_ID")).sendKeys("1965");
        driver.findElement(By.id("ageat_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Feb']")).click();
        }
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '10']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
    }

    @Test
    public void ageCalc6() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(500, 650));
        driver.findElement(By.linkText("Age Calculator")).click();
        driver.findElement(By.id("today_Month_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Month_ID"));
            dropdown.findElement(By.xpath("//option[. = 'Feb']")).click();
        }
        driver.findElement(By.id("today_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("today_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '24']")).click();
        }
        driver.findElement(By.id("today_Year_ID")).click();
        driver.findElement(By.id("today_Year_ID")).click();
        driver.findElement(By.id("today_Year_ID")).sendKeys("1991");
        driver.findElement(By.id("ageat_Day_ID")).click();
        {
            WebElement dropdown = driver.findElement(By.id("ageat_Day_ID"));
            dropdown.findElement(By.xpath("//option[. = '17']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(1)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".verybigtext"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".verybigtext"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".verybigtext"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".verybigtext")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("Age:\\\\n2 months 23 days\\\\nor 11 weeks 6 days\\\\nor 83 days\\\\nor 1,992 hours\\\\nor 119,520 minutes\\\\nor 7,171,200 seconds"));
        driver.findElement(By.cssSelector(".verybigtext")).click();
    }
}

