package cosc_603;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AutoLoanCalculatorTest extends BaseTest {

  @Test
  public void autoLoanCalculatorTest01() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("15000");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("60");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("5000");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("100");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Maryland']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("7");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("300");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $209.73"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$11,250.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$1,050.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$5,000.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$12,584.04"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$1,334.04"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$17,684.04"));
  }

  @Test
  public void autoLoanCalculatorTest02() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("20000");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("60");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("2500");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("0");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Delaware']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("6");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("300");
    }

    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $326.25"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$17,500.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$1,200.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$4,000.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$19,575.17"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$2,075.17"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$23,575.17"));
  }

  @Test
  public void autoLoanCalculatorTest03() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("12000");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("36");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("2000");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("1000");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Florida']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("5");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("500");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $301.21"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$10,050.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$550.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$2,000.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$10,843.47"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$793.47"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$13,843.47"));
  }

  @Test
  public void autoLoanCalculatorTest04() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("15000");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("48");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("3.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("1500");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("0");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Georgia']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("6");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("400");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $330.87"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$14,800.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$900.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$1,500.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$15,881.70"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$1,081.70"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$17,381.70"));
  }

  @Test
  public void autoLoanCalculatorTest05() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("30000");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("60");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("5000");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("2500");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Maryland']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("7");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("1000");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $477.26"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$25,600.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$2,100.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$5,000.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$28,635.68"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$3,035.68"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$36,135.68"));
  }

  @Test
  public void autoLoanCalculatorTest06() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("9750");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("60");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("0");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("0");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Maryland']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("6");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("450");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $201.06"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$10,785.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$585.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$0.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$12,063.90"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$1,278.90"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$12,063.90"));
  }

  @Test
  public void autoLoanCalculatorTest07() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("13500");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("24");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("0");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("1500");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Maryland']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("7");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("275");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $577.02"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$13,220.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$945.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$0.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$13,848.58"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$628.58"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$15,348.58"));
  }

  @Test
  public void autoLoanCalculatorTest08() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("22500");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("84");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("5000");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("2800");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Maryland']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("7");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("1200");
    }

    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $204.33"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$14,700.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$1,575.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$7,775.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$17,163.92"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$2,463.92"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$27,738.92"));
  }

  @Test
  public void autoLoanCalculatorTest09() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("18900");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("36");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("2500");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("0");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Colorado']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("5");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("1200");
    }

    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $487.85"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$16,400.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$945.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$4,645.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$17,562.58"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$1,162.58"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$22,207.58"));
  }

  @Test
  public void autoLoanCalculatorTest10() {
    driver.get("https://www.calculator.net/auto-loan-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.id("cloanamount"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanamount")).sendKeys("27000");

    }

    {
      WebElement element = driver.findElement(By.id("cloanterm"));
      element.clear();
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cloanterm")).sendKeys("60");
    }

    {
      WebElement element = driver.findElement(By.id("cinterestrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cinterestrate")).sendKeys("4.5");
    }

    {
      WebElement element = driver.findElement(By.id("cdownpayment"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("cdownpayment")).sendKeys("4000");
    }

    {
      WebElement element = driver.findElement(By.id("ctradeinvalue"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctradeinvalue")).sendKeys("0");
    }

    {
      WebElement dropdown = driver.findElement(By.name("cstate"));
      dropdown.findElement(By.xpath("//option[. = 'Alabama']")).click();
    }

    {
      WebElement element = driver.findElement(By.id("csaletax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("csaletax")).sendKeys("5");
    }

    {
      WebElement element = driver.findElement(By.id("ctitlereg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      driver.findElement(By.id("ctitlereg")).sendKeys("1200");
    }

    driver.findElement(By.cssSelector(".cbmark")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".h2result")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $476.33"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(1) > td:nth-child(2)")).getText(), is("$25,550.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(2) > td:nth-child(2)")).getText(), is("$1,350.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(3) > td:nth-child(2)")).getText(), is("$4,000.00"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(4) > td:nth-child(2)")).getText(), is("$28,579.75"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(5) > td:nth-child(2)")).getText(), is("$3,029.75"));
    assertThat(driver.findElement(By.cssSelector("td:nth-child(2) tr:nth-child(6) > td:nth-child(2)")).getText(), is("$32,579.75"));
  }

}
