package cosc_603;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class BmiCalculatorTest extends BaseTest {

  @Test
  public void bmiCalculatorTest01() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("30");
//    driver.findElement(By.cssSelector(".cbcontainer:nth-child(2) > .rbmark")).click();
//    driver.findElement(By.cssSelector(".cbcontainer:nth-child(1) > .rbmark")).click();

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("6");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("300");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font > b")).getText(), is("Obese Class II"));
  }

  @Test
  public void bmiCalculatorTest02() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("15");

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("300");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Overweight"));
  }

  @Test
  public void bmiCalculatorTest03() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("15");

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("150");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("At risk of overweight"));
  }

  @Test
  public void bmiCalculatorTest04() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("10");

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("8");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("150");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Overweight"));
  }

  @Test
  public void bmiCalculatorTest05() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("60");

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("6");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("0");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("185");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Overweight"));
  }

  @Test
  public void bmiCalculatorTest06() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("30");
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(1) > .rbmark")).click();

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("7");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("200");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font > b")).getText(), is("Obese Class I"));
  }

  @Test
  public void bmiCalculatorTest07() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("20");
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(1) > .rbmark")).click();

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("0");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("150");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("At risk of overweight"));
  }

  @Test
  public void bmiCalculatorTest08() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("60");
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(1) > .rbmark")).click();

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("160");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Overweight"));
  }

  @Test
  public void bmiCalculatorTest09() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("33");
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(1) > .rbmark")).click();

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("6");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("2");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("185");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Normal"));
  }

  @Test
  public void bmiCalculatorTest10() {
    driver.get("https://www.calculator.net/bmi-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.id("cage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cage")).sendKeys("16");
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(1) > .rbmark")).click();

    {
      WebElement element = driver.findElement(By.id("cheightfeet"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightfeet")).sendKeys("5");

    {
      WebElement element = driver.findElement(By.id("cheightinch"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cheightinch")).sendKeys("8");

    {
      WebElement element = driver.findElement(By.id("cpound"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cpound")).sendKeys("130");
    driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();

    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Healthy weight"));
  }
}
