package cosc_603;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class DueDateTest extends BaseTest {
  @Test
  public void dueDateTest1() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(617, 827));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    {
      WebElement element = driver.findElement(By.linkText("Pregnancy Calculator"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    assertThat(driver.getTitle(), is("Due Date Calculator"));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("cLastPeriodDay_Month_ID")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cLastPeriodDay_Month_ID"));
      dropdown.findElement(By.xpath("//option[. = 'May']")).click();
    }
    driver.findElement(By.id("cLastPeriodDay_Day_ID")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cLastPeriodDay_Day_ID"));
      dropdown.findElement(By.xpath("//option[. = '5']")).click();
    }
    driver.findElement(By.name("cCycleLength")).click();
    {
      WebElement dropdown = driver.findElement(By.name("cCycleLength"));
      dropdown.findElement(By.xpath("//option[. = '23 days']")).click();
    }
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
  }
  @Test
  public void dueDate2Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    assertThat(driver.findElement(By.cssSelector("table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td")).getText(), is("Estimate Based On: \n   \nLast Period\n   Ultrasound\n   Conception Date\n   IVF Transfer Date\n  "));
    assertThat(driver.findElement(By.cssSelector("#cilastperiod > tbody > tr:nth-child(1) > td:nth-child(1)")).getText(), is("First Day of Your Last Period:"));
    driver.findElement(By.cssSelector("#cilastperiod > tbody > tr:nth-child(2) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("#cilastperiod > tbody > tr:nth-child(2) > td:nth-child(1)")).getText(), is("Average Length of Your Cycles:"));
  }
  @Test
  public void dd3Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("cCycleLength")).click();
    {
      WebElement dropdown = driver.findElement(By.name("cCycleLength"));
      dropdown.findElement(By.xpath("//option[. = '40 days']")).click();
    }
    driver.findElement(By.id("cLastPeriodDay_Month_ID")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cLastPeriodDay_Month_ID"));
      dropdown.findElement(By.xpath("//option[. = 'Jun']")).click();
    }
    driver.findElement(By.id("cLastPeriodDay_Day_ID")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cLastPeriodDay_Day_ID"));
      dropdown.findElement(By.xpath("//option[. = '17']")).click();
    }
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".verybigtext")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("The estimated due date is Apr 5, 2021."));
  }
  @Test
  public void dd4Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("ccalcmethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("ccalcmethod"));
      dropdown.findElement(By.xpath("//option[. = 'Ultrasound']")).click();
    }
    driver.findElement(By.name("cUltrasoundWeek")).click();
    driver.findElement(By.name("cUltrasoundWeek")).sendKeys("120");
    driver.findElement(By.name("cUltrasoundDay")).click();
    driver.findElement(By.name("cUltrasoundDay")).sendKeys("1");
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".verybigtext")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("The estimated due date is Jan 19, 1597."));
  }
  @Test
  public void dd5Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.id("cLastPeriodDay_Month_ID")).click();
    driver.findElement(By.id("cLastPeriodDay_Day_ID")).click();
    driver.findElement(By.id("cLastPeriodDay_Year_ID")).click();
    driver.findElement(By.id("cLastPeriodDay_Year_ID")).sendKeys("1995");
    driver.findElement(By.cssSelector("#cilastperiod > tbody > tr:nth-child(2) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Result"));
  }
  @Test
  public void dd6Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("ccalcmethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("ccalcmethod"));
      dropdown.findElement(By.xpath("//option[. = 'Ultrasound']")).click();
    }
    driver.findElement(By.name("cUltrasoundWeek")).click();
    driver.findElement(By.name("cUltrasoundWeek")).sendKeys("10");
    driver.findElement(By.name("cUltrasoundDay")).click();
    driver.findElement(By.name("cUltrasoundDay")).sendKeys("1");
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".verybigtext")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("The estimated due date is Aug 20, 1978."));
  }
  @Test
  public void dd7Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("ccalcmethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("ccalcmethod"));
      dropdown.findElement(By.xpath("//option[. = 'Conception Date']")).click();
    }
    assertThat(driver.findElement(By.cssSelector("#ciconceptiondate > tbody > tr > td:nth-child(1)")).getText(), is("Conception Date:"));
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".verybigtext")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("The estimated due date is Dec 28, 2020."));
  }
  @Test
  public void dd8Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("ccalcmethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("ccalcmethod"));
      dropdown.findElement(By.xpath("//option[. = 'IVF Transfer Date']")).click();
    }
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(3) > .rbmark")).click();
    {
      WebElement element = driver.findElement(By.id("civfage4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("civfage4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("civfage4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#civf > tbody > tr:nth-child(2) > td:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#civf > tbody > tr:nth-child(2) > td:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#civf > tbody > tr:nth-child(2) > td:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#civf > tbody > tr:nth-child(2) > td:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#civf > tbody > tr:nth-child(2) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".cbcontainer:nth-child(3)")).getText(), is("day 6"));
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext > b")).getText(), is("Dec 14, 2020"));
  }
  @Test
  public void dd9Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("ccalcmethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("ccalcmethod"));
      dropdown.findElement(By.xpath("//option[. = 'IVF Transfer Date']")).click();
    }
    driver.findElement(By.id("civfage3")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".cbcontainer:nth-child(2) > .rbmark"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("civfage3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("civfage3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".cbcontainer:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#civf > tbody > tr:nth-child(2) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".cbcontainer:nth-child(2)")).getText(), is("day 5"));
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("The estimated due date is Dec 14, 2020."));
  }
  @Test
  public void test10Test() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(701, 825));
    driver.findElement(By.linkText("Due Date Calculator")).click();
    driver.findElement(By.name("ccalcmethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("ccalcmethod"));
      dropdown.findElement(By.xpath("//option[. = 'Conception Date']")).click();
    }
    driver.findElement(By.cssSelector("#cConceptionDay_ID_Link > img")).click();
    driver.findElement(By.cssSelector("#cConceptionDay_DayTable_ID tr:nth-child(4) > .calendarDateInput:nth-child(7)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector(".verybigtext")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("The estimated due date is Jan 16, 2021."));
  }

  private void assertTrue(Boolean isEditable) {

  }
}
