package cosc_603;
// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import static org.junit.Assert.assertThat;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GPACalculatorTest extends BaseTest{
    @Test
    public void test1() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(1)")).click();
        driver.findElement(By.name("da1")).click();
        driver.findElement(By.name("da1")).sendKeys("English");
        driver.findElement(By.name("da1")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("ca1")).click();
        driver.findElement(By.name("ca1")).sendKeys("3");
        driver.findElement(By.name("ca1")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("ca1")).click();
        driver.findElement(By.name("la1")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la1"));
            dropdown.findElement(By.xpath("//option[. = 'A+']")).click();
        }
        driver.findElement(By.cssSelector("table:nth-child(16) input")).click();
    }
    @Test
    public void test2() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(1)")).click();
        driver.findElement(By.name("da1")).click();
        driver.findElement(By.name("da1")).sendKeys("Writing");
        driver.findElement(By.name("da1")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("ca1")).click();
        driver.findElement(By.name("ca1")).sendKeys("3");
        driver.findElement(By.name("ca1")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("la1")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la1"));
            dropdown.findElement(By.xpath("//option[. = 'A+']")).click();
        }
        driver.findElement(By.name("da1")).click();
        assertThat(driver.getTitle(), is("GPA Calculator"));
        driver.findElement(By.cssSelector("table:nth-child(16) input")).click();
    }
    @Test
    public void test3() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".clearbtn:nth-child(1)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".clearbtn:nth-child(1)")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.name("ca1")).click();
        driver.findElement(By.name("ca1")).sendKeys("4");
        driver.findElement(By.name("la1")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la1"));
            dropdown.findElement(By.xpath("//option[. = 'C+']")).click();
        }
        driver.findElement(By.name("ca2")).click();
        driver.findElement(By.name("ca2")).sendKeys("2");
        driver.findElement(By.name("la2")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la2"));
            dropdown.findElement(By.xpath("//option[. = 'B+']")).click();
        }
        {
            String value = driver.findElement(By.name("da1")).getAttribute("value");
            assertThat(value, is(""));
        }
        driver.findElement(By.name("gpaform")).click();
        driver.findElement(By.cssSelector("table:nth-child(16) input")).click();
    }
    @Test
    public void test4() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(1)")).click();
        driver.findElement(By.name("da1")).click();
        driver.findElement(By.name("da1")).sendKeys("Math");
        driver.findElement(By.name("ca1")).click();
        driver.findElement(By.name("ca1")).sendKeys("4");
        driver.findElement(By.name("da2")).click();
        driver.findElement(By.name("da2")).sendKeys("Math Lab");
        driver.findElement(By.name("ca2")).click();
        driver.findElement(By.name("ca2")).sendKeys("1");
        driver.findElement(By.name("ca3")).click();
        driver.findElement(By.name("ca3")).sendKeys("6");
        driver.findElement(By.name("la1")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la1"));
            dropdown.findElement(By.xpath("//option[. = 'A+']")).click();
        }
        driver.findElement(By.name("la2")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la2"));
            dropdown.findElement(By.xpath("//option[. = 'C+']")).click();
        }
        driver.findElement(By.name("la3")).click();
        {
            WebElement dropdown = driver.findElement(By.name("la3"));
            dropdown.findElement(By.xpath("//option[. = 'B-']")).click();
        }
        driver.findElement(By.name("la3")).click();
        driver.findElement(By.cssSelector("td:nth-child(3) > b")).click();
        {
            List<WebElement> elements = driver.findElements(By.linkText("+ add more courses"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.cssSelector("table:nth-child(16) input")).click();
    }
    @Test
    public void test5() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(1)")).click();
        driver.findElement(By.cssSelector("td > table:nth-child(2) tr:nth-child(1) > td:nth-child(1)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("td > table:nth-child(2) tr:nth-child(1) > td:nth-child(1)"));
            Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
            assertTrue(isEditable);
        }
        driver.findElement(By.cssSelector("table:nth-child(16) input")).click();
    }
    @Test
    public void test6Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.name("grcCurrentGPA")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(3)")).click();
        driver.findElement(By.name("grcCurrentGPA")).click();
        driver.findElement(By.name("grcCurrentGPA")).sendKeys(Keys.ENTER);
        {
            String value = driver.findElement(By.name("grcCurrentGPA")).getAttribute("value");
            assertThat(value, is(""));
        }
        driver.findElement(By.cssSelector("form:nth-child(14) > .panel")).click();
    }
    @Test
    public void test7() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(3)")).click();
        driver.findElement(By.name("grcCurrentGPA")).click();
        {
            WebElement element = driver.findElement(By.name("grcCurrentGPA"));
            Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
            assertTrue(isEditable);
        }
        driver.findElement(By.name("grcCurrentGPA")).sendKeys("3.8");
        driver.findElement(By.name("grcTargetGPA")).click();
        driver.findElement(By.name("grcTargetGPA")).sendKeys("4.0");
        driver.findElement(By.name("grcCurrentCredit")).click();
        driver.findElement(By.name("grcCurrentCredit")).sendKeys("50");
        driver.findElement(By.name("grcAdditionalCredit")).click();
        driver.findElement(By.name("grcAdditionalCredit")).sendKeys("12");
        driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    }
    @Test
    public void test8() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        assertThat(driver.findElement(By.cssSelector(".panel tr:nth-child(4) > td:nth-child(1)")).getText(), is("Additional Credits"));
        driver.findElement(By.cssSelector(".clearbtn:nth-child(3)")).click();
        driver.findElement(By.name("grcCurrentGPA")).click();
        driver.findElement(By.name("grcCurrentGPA")).sendKeys("3.0");
        driver.findElement(By.name("grcTargetGPA")).click();
        driver.findElement(By.name("grcTargetGPA")).sendKeys("3.75");
        driver.findElement(By.name("grcCurrentCredit")).click();
        driver.findElement(By.name("grcCurrentCredit")).sendKeys("9");
        driver.findElement(By.name("grcAdditionalCredit")).click();
        driver.findElement(By.name("grcAdditionalCredit")).sendKeys("9");
        driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    }
    @Test
    public void test9() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn:nth-child(3)")).click();
        driver.findElement(By.name("grcCurrentGPA")).click();
        driver.findElement(By.name("grcCurrentGPA")).sendKeys("3.3");
        driver.findElement(By.name("grcTargetGPA")).click();
        driver.findElement(By.name("grcTargetGPA")).sendKeys("4.0");
        driver.findElement(By.name("grcCurrentCredit")).click();
        driver.findElement(By.name("grcCurrentCredit")).sendKeys("15");
        driver.findElement(By.name("grcAdditionalCredit")).click();
        driver.findElement(By.name("grcAdditionalCredit")).sendKeys("12");
        assertThat(driver.findElement(By.cssSelector(".panel tr:nth-child(4) > td:nth-child(1)")).getText(), is("Additional Credits"));
        driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
    }
    @Test
    public void test10() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("GPA Calculator")).click();
        driver.findElement(By.linkText("+ add more courses")).click();
        assertFalse(driver.findElement(By.linkText("+ add more courses")).isSelected());
        driver.findElement(By.cssSelector("table:nth-child(16) input")).click();
        driver.findElement(By.name("da1")).click();
        driver.findElement(By.name("da1")).sendKeys("English");
        driver.findElement(By.name("da1")).sendKeys(Keys.ENTER);
    }
}
