package cosc_603;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class MortgageCalcTest extends BaseTest {

    @Test
    public void mortgageCalc1() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Mortgage Calculator")).click();
        driver.findElement(By.cssSelector("td:nth-child(1) > input:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".h2result"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".h2result"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".h2result"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".h2result")).click();
        assertThat(driver.findElement(By.cssSelector(".h2result")).getText(), is("Monthly Pay:   $1,088.45"));
        driver.findElement(By.cssSelector(".h2result")).click();
    }



}
