package cosc_603;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SaleTaxCalcTest extends BaseTest {

    @Test
    public void salesTaxCalc0() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 6.50% or $6.50"));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    }
    @Test
    public void salesTaxCalc1() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("10.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $110.50"));
        driver.findElement(By.id("content")).click();
    }
    @Test
    public void salesTaxCalc2() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("170");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("12.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $170.00"));
        driver.findElement(By.cssSelector("h1")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $191.25"));
        driver.findElement(By.id("content")).click();
    }
    @Test
    public void salesTaxCalc3() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("1200");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("9.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 9.50% or $114.00"));
        driver.findElement(By.id("content")).click();
    }
    @Test
    public void salesTaxCalc4() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("70");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("12.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $78.75"));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    }
    @Test
    public void salesTaxCalc5() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("120");
        driver.findElement(By.cssSelector("table:nth-child(1) tr:nth-child(2) > td:nth-child(1)")).click();
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("9.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $131.40"));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
        driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is(not("After Sale")));
        driver.findElement(By.cssSelector(".h2result")).click();
    }
    @Test
    public void salesTaxCalc6() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("30");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("7.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $30.00"));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
        driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is(not("Apple Pie")));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).click();
    }
    @Test
    public void salesTaxCalc7() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("175");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("2.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $179.38"));
        driver.findElement(By.id("content")).click();
    }
    @Test
    public void salesTaxCalc8() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("250");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("23.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $308.75"));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
        driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
        assertThat(driver.getTitle(), is("Sales Tax Calculator"));
        driver.findElement(By.cssSelector("h1")).click();
    }
    @Test
    public void salesTaxCalc9() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(819, 447));
        driver.findElement(By.linkText("Sales Tax Calculator")).click();
        driver.findElement(By.name("beforetax")).click();
        driver.findElement(By.name("beforetax")).sendKeys("200");
        driver.findElement(By.name("taxrate")).click();
        driver.findElement(By.name("taxrate")).sendKeys("11.5");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $223.00"));
        driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
        driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
    }
}

