// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SalesTaxCalculator01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void salesTaxCalculator01() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    driver.findElement(By.name("beforetax")).click();
    driver.findElement(By.name("beforetax")).click();
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys("1200");
    driver.findElement(By.name("taxrate")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,200.00"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).click();
    driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).getText(), is("$78.00"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6) b")).getText(), is("$1,278.00"));
  }
}
