// Generated by Selenium IDE

package cosc_603;


import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class SalesTaxCalculator01Test extends BaseTest {

  @Test
  public void salesTaxCalculator01() throws InterruptedException {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys("1200");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,200.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).getText(), is("$78.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6) b")).getText(), is("$1,278.00"));
  }
}
