// Generated by Selenium IDE

package cosc_603;


import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class SalesTaxCalculatorTest extends BaseTest {

  @Test
  public void salesTaxCalculatorTest01() throws InterruptedException {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys("1200");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,200.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).getText(), is("$78.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6) b")).getText(), is("$1,278.00"));
  }

  @Test
  public void salesTaxCalculatorTest02() throws InterruptedException {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys(" ");
    {
      WebElement element = driver.findElement(By.name("finalprice"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("finalprice")).sendKeys("5000");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    Thread.sleep(5000);
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $4,694.84"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).getText(), is("$305.16"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $5,000.00"));
  }

  @Test
  public void salesTaxCalculatorTest03() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    driver.findElement(By.name("beforetax")).click();
    driver.findElement(By.name("beforetax")).click();
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys("89.76");
    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("taxrate")).sendKeys("3.4");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $89.76"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).getText(), is("$3.05"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6) b")).getText(), is("$92.81"));
  }

  @Test
  public void salesTaxCalculatorTest04() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    driver.findElement(By.name("taxrate")).click();
    driver.findElement(By.name("taxrate")).click();
    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("taxrate")).sendKeys(" ");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Please provide at least two values to calculate."));
    driver.close();
  }

  @Test
  public void salesTaxCalculatorTest05() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys("1234");

    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    driver.findElement(By.name("taxrate")).sendKeys(" ");
    driver.findElement(By.name("finalprice")).sendKeys("1400");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,234.00"));

    driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 13.45% or $166.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $1,400.00"));
  }

  @Test
  public void salesTaxCalculatorTest06() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys(" ");

    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    driver.findElement(By.name("taxrate")).sendKeys("5");
    driver.findElement(By.name("finalprice")).sendKeys("1400");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,333.33"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 5.00% or $66.67"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $1,400.00"));
  }

  @Test
  public void salesTaxCalculatorTest07() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys(" ");

    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    driver.findElement(By.name("taxrate")).sendKeys("4.75");
    driver.findElement(By.name("finalprice")).sendKeys("500000");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $477,326.97"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 4.75% or $22,673.03"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $500,000.00"));
  }

  @Test
  public void salesTaxCalculatorTest08() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));

    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("taxrate")).sendKeys(" ");

    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys(" ");

    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Please provide at least two values to calculate."));
    driver.close();
  }

  @Test
  public void salesTaxCalculatorTest09() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys("1500");

    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("taxrate")).sendKeys("5");

    driver.findElement(By.name("finalprice")).sendKeys("1600");

    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,500.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 5.00% or $75.00"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $1,575.00"));
  }

  @Test
  public void salesTaxCalculatorTest10() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys(" ");

    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("taxrate")).sendKeys("5");

    driver.findElement(By.name("finalprice")).sendKeys("1600");

    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();

    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $1,523.81"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).getText(), is("Sale Tax: 5.00% or $76.19"));
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $1,600.00"));
  }
}
