package cosc_603;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class SalesTaxCalculator02Test extends BaseTest {

  @Test
  public void salesTaxCalculator02() throws InterruptedException {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    {
      WebElement element = driver.findElement(By.name("beforetax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("beforetax")).sendKeys(" ");
    {
      WebElement element = driver.findElement(By.name("finalprice"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("finalprice")).sendKeys("5000");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    Thread.sleep(5000);
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(4)")).getText(), is("Before Tax Price: $4,694.84"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(5) b")).getText(), is("$305.16"));
    driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector(".verybigtext:nth-child(6)")).getText(), is("After Tax Price: $5,000.00"));
  }
}
