package cosc_603;// Generated by Selenium IDE

import cosc_603.BaseTest;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class SalesTaxCalculator04Test extends BaseTest {

  @Test
  public void salesTaxCalculator04() {
    driver.get("https://www.calculator.net/sales-tax-calculator.html");
    driver.manage().window().setSize(new Dimension(1680, 1027));
    driver.findElement(By.name("taxrate")).click();
    driver.findElement(By.name("taxrate")).click();
    {
      WebElement element = driver.findElement(By.name("taxrate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("taxrate")).sendKeys(" ");
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Please provide at least two values to calculate."));
    driver.close();
  }
}
