package cosc_603;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import static org.junit.Assert.assertThat;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

public class TriangleCalculatorTest extends BaseTest {
  
    @Test
    public void triangle1Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td")).getText(), is("Angle Unit: \n     \ndegree °\n     radian\n    "));
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
    }
  
    @Test
    public void triangle2Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".clearbtn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".clearbtn")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.name("vc")).click();
        driver.findElement(By.name("vc")).sendKeys("90");
        driver.findElement(By.name("va")).click();
        driver.findElement(By.name("va")).sendKeys("180");
        driver.findElement(By.name("vy")).click();
        driver.findElement(By.name("vy")).sendKeys("1");
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("p:nth-child(4)")).click();
        driver.findElement(By.cssSelector("p:nth-child(4)")).click();
        driver.findElement(By.cssSelector("p:nth-child(4)")).click();
        assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Angle \"a\" too big."));
    }
  
    @Test
    public void triangle3Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.name("va")).click();
        driver.findElement(By.name("va")).sendKeys("110");
        driver.findElement(By.name("vb")).click();
        driver.findElement(By.name("vb")).sendKeys("60");
        driver.findElement(By.name("vx")).click();
        driver.findElement(By.name("vx")).sendKeys("1");
        {
            String value = driver.findElement(By.name("va")).getAttribute("value");
            assertThat(value, is("110"));
        }
        {
            String value = driver.findElement(By.name("vb")).getAttribute("value");
            assertThat(value, is("60"));
        }
        {
            String value = driver.findElement(By.name("vx")).getAttribute("value");
            assertThat(value, is("1"));
        }
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("td > h3")).click();
        assertThat(driver.findElement(By.cssSelector("td > h3")).getText(), is("Obtuse Scalene Triangle"));
    }
  
    @Test
    public void triangle4Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("tr:nth-child(5) input"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.name("va")).click();
        driver.findElement(By.name("va")).sendKeys("30");
        driver.findElement(By.name("vx")).click();
        driver.findElement(By.name("vx")).sendKeys("1");
        driver.findElement(By.name("vy")).click();
        driver.findElement(By.name("vy")).sendKeys("1");
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("td > h3")).click();
        assertThat(driver.findElement(By.cssSelector("td > h3")).getText(), is("Obtuse Isosceles Triangle"));
    }
  
    @Test
    public void triangle5Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.name("vc")).click();
        driver.findElement(By.name("vc")).sendKeys("80");
        driver.findElement(By.name("va")).click();
        driver.findElement(By.name("va")).sendKeys("60");
        driver.findElement(By.name("vz")).click();
        driver.findElement(By.name("vz")).sendKeys("1");
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("td > h3")).click();
        assertThat(driver.findElement(By.cssSelector("td > h3")).getText(), is("Equilateral Triangle"));
    }
  
    @Test
    public void triangle6Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".clearbtn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".clearbtn")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.name("vc")).click();
        driver.findElement(By.name("vc")).sendKeys("60");
        driver.findElement(By.name("vx")).click();
        driver.findElement(By.name("vx")).sendKeys("1");
        driver.findElement(By.name("vb")).click();
        driver.findElement(By.name("vb")).sendKeys("70");
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("td > h3")).click();
        assertThat(driver.findElement(By.cssSelector("td > h3")).getText(), is("Acute Scalene Triangle"));
    }
  
    @Test
    public void triangle7Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("font")).click();
        assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Please provide 3 positive values, including at least one side."));
        {
            String value = driver.findElement(By.name("vc")).getAttribute("value");
            assertThat(value, is(""));
        }
        driver.findElement(By.cssSelector("td:nth-child(1) tr:nth-child(2) > td:nth-child(1)")).click();
        {
            String value = driver.findElement(By.name("vx")).getAttribute("value");
            assertThat(value, is(""));
        }
    }
  
    @Test
    public void triangle8Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.name("vb")).click();
        driver.findElement(By.name("vb")).sendKeys("90");
        driver.findElement(By.name("vc")).click();
        driver.findElement(By.name("vc")).sendKeys("10");
        driver.findElement(By.name("vx")).click();
        driver.findElement(By.name("vx")).sendKeys("1");
        driver.findElement(By.cssSelector("td:nth-child(1) tr:nth-child(2) > td:nth-child(1)")).click();
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("td > h3")).click();
        assertThat(driver.findElement(By.cssSelector("td > h3")).getText(), is("Right Scalene Triangle"));
    }
  
    @Test
    public void triangle9Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".clearbtn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.name("vc")).click();
        driver.findElement(By.name("vc")).sendKeys("90");
        driver.findElement(By.name("va")).click();
        driver.findElement(By.name("va")).sendKeys("90");
        driver.findElement(By.name("vx")).click();
        driver.findElement(By.name("vx")).sendKeys("1");
        driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
        driver.findElement(By.cssSelector("font")).click();
        assertThat(driver.findElement(By.cssSelector("font")).getText(), is("These three values can not be used to create an valid triangle."));
    }
  
    @Test
    public void triangle10Test() {
        driver.get("https://www.calculator.net/");
        driver.manage().window().setSize(new Dimension(701, 825));
        driver.findElement(By.linkText("Triangle Calculator")).click();
        driver.findElement(By.cssSelector(".clearbtn")).click();
        driver.findElement(By.name("vb")).click();
        driver.findElement(By.name("vb")).sendKeys("10");
        driver.findElement(By.name("vc")).click();
        driver.findElement(By.name("vc")).sendKeys("110");
        driver.findElement(By.name("va")).click();
        driver.findElement(By.name("va")).sendKeys("20");
        driver.findElement(By.name("va")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("font")).click();
        assertThat(driver.findElement(By.cssSelector("font")).getText(), is("Please provide one side."));
    
    }
}
