language: java
jdk:
 - openjdk8
sudo: required
dist: xenial
addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &

install:
  - wget -N http://chromedriver.storage.googleapis.com/83.0.4103.14/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver

notifications:
  email:
    recipients:
      - firminsa@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
